# Generated by Django 5.1.4 on 2025-03-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='preuser', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
