# Generated by Django 5.1.4 on 2025-06-14 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('is_full', models.BooleanField(default=False)),
                ('code_diff', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='base.room')),
            ],
            options={
                'ordering': ['version_number'],
                'unique_together': {('room', 'version_number')},
            },
        ),
    ]
