# Generated by Django 5.1.4 on 2025-06-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_codesnippets'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['id'], name='base_room_id_cb35dd_idx'),
        ),
    ]
