# Generated by Django 5.1.4 on 2025-06-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_base_room_id_cb35dd_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='codesnippets',
            index=models.Index(fields=['room', '-version_number'], name='base_codesn_room_id_00cea5_idx'),
        ),
    ]
