# Generated by Django 5.1.4 on 2024-12-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_roominvitation_roommembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommembership',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('OUTSIDER', 'Outsider')], default='OUTSIDER', max_length=10),
        ),
    ]
